### ISSUE TITLE
Same channel from multiple video sources show up as seperate channels in Kodi

### ISSUE THREAD

**Issue by lentferj** [janbar/xbmc-pvr-addons#29] opened 2014-12-10 11:20 UTC
I have mythtv 0.27.3 and now switched to Kodi 14 RC3 and latest mythtv pvr from git as of 1 hour ago. In mythtv I have 3 video sources configured (DVB-S, DVB-T and IPTV) - so I have the same channels twice or three times - one on each of the video sources. The "same" channels in mythtv also have the same channel number and name. In mythtv this leads to the channel only being shown as one and having mythtv decide which video source and tuner to use to stream the selected channel. It was also like this prior upgrading to Kodi 14 RC3 and the latest pvr addon. Now I have each channel 3 times in the list on Kodi with the same channel number (enabled channel numbering from backend).

**Comment by robho** [comment] 2015-02-10 21:14
To avoid duplicated channels the recommendation has previously been to set identical chanid for the channels you want merged (http://www.gossamer-threads.com/lists/mythtv/users/557044) and mythweb (at least 0.27) merges channels with same ids.

Has something changed in mythtv? Otherwise I think it would make sense if the addon uses the same strategy as mythtv itself. If a user wants to avoid merging channels then the chanids can be made unique (and I think they are unique by default since I had to manually set them to enable merging).

**Comment by robho** [comment] 2015-02-10 21:34
Sorry, when I wrote chanid I actually meant channum.

**Comment by fatg3erman** [comment] 2015-02-25 20:07
Yeah this is true, I discussed this with the mythtv guys when I set my mythtv system up. Channel Number has no meaning other than to permit grouping of channels when you have the same channel present on multiple sources. Each channel number should only be displayed once in any frontend - the backend chooses which source to use when LiveTV is started. I don't think people have a specific 'livestream' source - they just have multiple sources so enable multiple simultaneous recordings.

**Comment by janbar** [comment] 2015-02-26 00:07
Please, discuss in the forum http://forum.kodi.tv/showthread.php?tid=198833 about to decide what is the best. Few months ago we have discussed about and users choosen to not merge channels across sources. Discussion is in the same forum.

**Comment by fatg3erman** [comment] 2015-02-26 09:42
Sorry I didn't realise it had already been discussed. To me the current decision seems very, very strange :) Can I then request that this is changed from a question to a feature request? That channel merging can be a configuration option?

To explain, here's why the current state doesn't work for me:
1. In the EPG because there are so many duplicate channels I only see half the amount of information I could.
2. In the EPG I have > 200 channels to scroll through, most of which are duplicates.
3. Choosing to display only one channel group doesn't help because each of my sources has some unique channels - so if I do this some channels are always missing. (Kodi's channel groups model makes assumptions that are not always true for mythtv)
4. The entire way my myth backend is set up is so that myth's scheduler can choose which tuner to record on at any time. The frontend should not make decisions about this - this is what the myth guys recommend and it's the only way to get a setup like mine to work properly.
5. So, I don't have one source for livetv and another for recording. I have 2 sources which have an overlapping set of channels and myth backend chooses the most appropriate source to record on. It's supposed to be transparent to the user but with the current Kodi implementation of channel groups it cannot be.

**Comment by janbar** [comment] 2015-02-26 19:40
I will review it to find the best solution and so we have to add a setting to enable/disable the merging.

**Comment by fatg3erman** [comment] 2015-02-26 19:48
You're the man. Thanks :)

**Comment by janbar** [comment] 2015-02-26 23:59
I pushed a branch named "channel_merging". It contains code to merge channels accross sources. If you can compile it and test it , it would be great. It is compatible with helix.

**Comment by janbar** [comment] 2015-02-27 00:03
to get the branch: <pre>git clone -b channel_merging https://github.com/janbar/xbmc-pvr-addons.git</pre>

**Comment by fatg3erman** [comment] 2015-02-27 00:06
I will try this but can you help me by giving me some details on how to build and install it? I've never done this before. I currently have kodi-pvr-mythtv-helix installed from your PPA.

**Comment by janbar** [comment] 2015-02-27 00:09
Ok, tomorrow i will make a brief tuto for you

**Comment by MikeB2013** [comment] 2015-02-27 11:06
@janbar 
The merge works fine on my mythtv 0.27 fixes test system, I have 2 sources DVB-T and DVB-S/S2.
However when in All Channels mode, I get channel unavailable if there are no free recorders for the first chanid. I think it needs to iterate through all possible chanid's associated with the channum when opening a LiveTV stream. 

mysql> select channum, name,callsign, chanid,sourceid from channel where channum=130;
+---------+----------+----------+--------+----------+
| channum | name     | callsign | chanid | sourceid |
+---------+----------+----------+--------+----------+
| 130     | BBC NEWS | BBC NEWS |   1130 |        1 |
| 130     | BBC NEWS | BBC NEWS |  12358 |        2 |
+---------+----------+----------+--------+----------+
2 rows in set, 2 warnings (0.00 sec)

mysql> select channum, name,callsign, chanid,sourceid from channel where channum=132;
+---------+----------+----------+--------+----------+
| channum | name     | callsign | chanid | sourceid |
+---------+----------+----------+--------+----------+
| 132     | Sky News | Sky News |   1132 |        1 |
| 132     | Sky News | Sky News |   6704 |        2 |
+---------+----------+----------+--------+----------+
2 rows in set, 2 warnings (0.00 sec)

Mike

**Comment by janbar** [comment] 2015-02-27 18:33
Yes we have to iterate for each merged channel. The first commit allows us to check kodi displays right  all channel groups and the global view.
The iteration could be simple without care of prefered live tv order.
JLB

**Comment by janbar** [comment] 2015-02-27 20:58
About issue #36 , the addon never interferes with others recordings. There the root cause is in backend itself. Addon only ask from the backend a free recorder, check list of free inputs matching with the channel and finally ask to spawn channel if available.

**Comment by janbar** [comment] 2015-02-28 03:00
@MikeB2013 i pushed 3 new commits to the branch "channel_merging". Here i haven't any regression and prefered liveTV order is used to choose encoder and finally live is spawn from any channel with same Number/CallSign. Let me know if you suspect any regression with more than one source. Thanks.

**Comment by MikeB2013** [comment] 2015-02-28 14:30
LiveTV order works  on mythtv 0.27 fixes using Helix Kodi (14.2-BETA2 Git:2015-02-27-aacffbe-dirty). Platform: Linux x86 64-bit

 Does not work on mythtv 0.28pre debug log is http://xbmclogs.com/pna4sw2xz
Here is extract from mythconverg table:
mysql> select cardid,sourceid,displayname,livetvorder,schedorder from capturecard;
+--------+----------+-------------+-------------+------------+
| cardid | sourceid | displayname | livetvorder | schedorder |
+--------+----------+-------------+-------------+------------+
|      1 |        4 | FV-1        |          16 |          1 |
|      2 |        4 | FV-1        |          16 |          1 |
|      3 |        4 | FV-1        |          16 |          1 |
|      4 |        4 | FV-1        |          16 |          1 |
|      5 |        4 | FV-1        |          16 |          1 |
|      6 |        4 | FV-2        |          11 |          6 |
|      7 |        4 | FV-2        |          11 |          6 |
|      8 |        4 | FV-2        |          11 |          6 |
|      9 |        4 | FV-2        |          11 |          6 |
|     10 |        4 | FV-2        |          11 |          6 |
|     11 |        5 | FS-1        |           6 |         11 |
|     12 |        5 | FS-1        |           6 |         11 |
|     13 |        5 | FS-1        |           6 |         11 |
|     14 |        5 | FS-1        |           6 |         11 |
|     15 |        5 | FS-1        |           6 |         11 |
|     16 |        5 | FS-2        |           1 |         16 |
|     17 |        5 | FS-2        |           1 |         16 |
|     18 |        5 | FS-2        |           1 |         16 |
|     19 |        5 | FS-2        |           1 |         16 |
|     20 |        5 | FS-2        |           1 |         16 |
+--------+----------+-------------+-------------+------------+
20 rows in set (0.00 sec)
The above order means that preferred order for livetv is FS-2,FS-1,FV-2, FV-1

Mike

**Comment by janbar** [comment] 2015-02-28 16:12
Seems 'livetvorder' and 'schedorder' are swapped ! 'schedorder' has been added with 0.28.

**Comment by janbar** [comment] 2015-02-28 16:23
@MikeB2013 Thanks, good catch ! I don't remember where i have seen the spec of inputInfo, but mine is totally wrong. I am fixing ...

**Comment by janbar** [comment] 2015-02-28 17:31
Fixed and now the channel merging is the default behavior as mythfrontend. So any user wants duplicate channel across sources, has to update the chanNum/callSign to be unique.

**Closed by janbar** 2015-02-28 17:31 UTC
Labels: enhancement

**Comment by janbar** [comment] 2015-02-28 17:34
The fixes are merged in helix and gotham branches. Also the master branch is frozen/discontinued since addons are splitted (xbmc PR 6227). The new repository is named "pvr.mythtv" : https://github.com/janbar/pvr.mythtv/

**Comment by janbar** [comment] 2015-02-28 17:37
@MikeB2013 do you need i will update the wiki@kodi to build addon from source with the new build-system ?

**Comment by MikeB2013** [comment] 2015-02-28 17:41
@janbar 
The following is from my mythtv 0.27
mysql> select cardid,sourceid,displayname,livetvorder,schedorder from cardinput;
+--------+----------+-------------+-------------+------------+
| cardid | sourceid | displayname | livetvorder | schedorder |
+--------+----------+-------------+-------------+------------+
|      1 |        1 | FV-Test-1   |          11 |          1 |
|      2 |        1 | FV-Test-1   |          11 |          1 |
|      3 |        1 | FV-Test-1   |          11 |          1 |
|      4 |        1 | FV-Test-1   |          11 |          1 |
|      5 |        1 | FV-Test-1   |          11 |          1 |
|      6 |        2 | FS-test-1   |           6 |          6 |
|      7 |        2 | FS-test-1   |           6 |          6 |
|      8 |        2 | FS-test-1   |           6 |          6 |
|      9 |        2 | FS-test-1   |           6 |          6 |
|     10 |        2 | FS-test-1   |           6 |          6 |
|     11 |        2 | FS-test-2   |           1 |         11 |
|     12 |        2 | FS-test-2   |           1 |         11 |
|     13 |        2 | FS-test-2   |           1 |         11 |
|     14 |        2 | FS-test-2   |           1 |         11 |
|     15 |        2 | FS-test-2   |           1 |         11 |
+--------+----------+-------------+-------------+------------+
15 rows in set (0.00 sec)

In 0.28pre there was a change some weeks ago  (16 Jan 2015)  that deprecated cardinput table and moved livetvorder and others to capturecard table. https://github.com/MythTV/mythtv/commit/3e8bd6bf460913d3705e945f3bd5d409d1c3c257

Mike

**Comment by MikeB2013** [comment] 2015-02-28 17:45
@janbar,

Thanks for the updates.
Yes, new build instructions for pvr.mythtv would be good so I can test on my Raspberry Pi 2 (Openelec), 

Mike
