### ISSUE TITLE
Addon ignores backend tuner priorities, interferes with recordings when not necesarry

### ISSUE THREAD

**Issue by daseidl** [janbar/xbmc-pvr-addons#36] opened 2015-02-21 16:21 UTC
My setup:

Server:
Debian Wheezy (Kernel updated to 3.16.7)
Mythtv-backend: 0.26.2-dmo1
DVB-S2 dual tuner card: Digital Devices Cine S2 V6.5  +   CI-Module with ORF Smartcard configured to be used with tuner 1
(Unfortunately the Linux drivers for the DVB-S2 card doesn't support the use of both tuner sharing the CI module yet)

Mythtv is configured, to do 2 recordings in parallel per tuner, so I see 4 virtual tuners in mythweb.
Virtual tuner 1,2 can record all channels (including encrypted ORF via CI module), tuner 3,4 can only record FreeTV. Tuner 3,4 are configured to be preferred whenever possible.

=================
Client:
3x Raspberry Pi B, using raspbmc, Kodi 14.2 nightly build

--------------------------------------------
Situation:

As long as I only use Mythtv/Mythweb, everything woks exactly as it's supposed to be.
I can watch/record up to 4 channels in parallel (depending on the transponder), but independent on the order I start recording/ watching.

However,
the Mythtv-plugin ignores the preferred tuner, that results in a problem if I want to:
1 start to watch a FreeTV channel. Tuner 1 will be used for this.
2 start to watch/record PayTV (ORF). Not possible any more, because Tuner 1 is already occupied.

Furthermore, It is possible to record/ watch ORF1 and ORF2 in parallel when using mythweb using virtual tuner 1,2 because they share a transponder.
With the plugin, live-tv stops as soon the back-end starts to record, which wouldn't be necessary.

**Comment by janbar** [comment] 2015-02-27 21:30
HI @daseidl , thanks to report issue. In this issue there is few different points:
- Preferred liveTV order: Currently we reviewing to re-enable the channel merging which is requires to take care of preferred order. It is processed with issue #29.
- The sharing of transponder is handled by the backend, not the addon: Addon only ask from the backend for **free** recorder, then it checks if the channel is tunable with this recorder comparing available multiplex, and finally ask to spawn. Root cause of live-tv stops is in the backend and i cannot do anything to resolve it. I recommend you to upgrade your backend to version 0.27 which is also the minimum supported version by the addon.
Probably resolving #29 could resolve a part of this issue. Soon i will propose a new version including the enhancement. Others point would be resolve upgrading your backend.

**Comment by janbar** [comment] 2015-02-28 17:39
@daseidl , the #29 is now fixed/merged in helix/gotham branches. You could try the new version of addon helix 1.12.7. Let me know, thanks.

**Closed** 2015-03-05 19:31 UTC
